### ISSUE TITLE
Success Alert and clear inputs.

### ISSUE THREAD

**Issue by pieinn** [ferdinandfrank/vue-forms#4]
Sorry for disturb again,
Please advice how to show Success Alert and clear inputs.

All inputs not cleared when submit form

My Controller : return redirect()->back()->withInput();

Thank you for awesome package.

**Comment by ferdinandfrank** [comment]
To clear the inputs after the form has been successfully submitted, you can simply add the prop `clear` with the value `true` to your `AjaxFormComponent`:

```html
<ajax-form method="post" action="path/to/server" :clear=true>
...
</ajax-form>
```

To show a success alert message after the request was processed by the server, the server should return a json response like the following:

```php
return response()->json([
    'alert' => [
        'title'   => 'Success',
        'message' => 'The request was successful!'
    ]
]);
```
You can view the full list of json params for the response [here](https://ferdinandfrank.github.io/vue-forms/#server-response-handling).
I will make a better documentation within the next days!

**Comment by pieinn** [comment]
Thank you very much! Please provide with some samples
